# Generated by Django 2.0 on 2017-12-18 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
        ('human', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='human',
            name='room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='room.Room'),
            preserve_default=False,
        ),
    ]
