# Generated by Django 2.0 on 2017-12-19 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='human',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='human.Human'),
        ),
        migrations.AlterField(
            model_name='key',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='room.Room'),
        ),
    ]
